# Jekyll configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 10
language: "en-uk"

# Website info
name: "sohnjunior의 Dev Log"
description: "PS와 웹 개발 관련내용을 기록합니다."

short_url: "sohnjunior.github.io/"
google_analytics: UA-69281367-1
disqus: jekyllblog-2
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: "/"
url: "https://sohnjunior.github.io"

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
plugins: [jekyll-paginate]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: sohnjunior
repo: https://github.com/sohnjunior/sohnjunior.github.io.git
branch: master
relative_source: ../
destination: ./_site/
production_url: https://sohnjunior.github.io/
source_url: https://github.com/sohnjunior/sohnjunior.github.io/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - .git

include:
  - .nojekyll
